name: Generate Podcast Feeds
on: [push]
jobs: 
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      
      - name: Setup Python
        uses: actions/setup-python@v4
        with: 
          python-version: '3.10'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyyaml

      - name: Run Feed Generator
        run: python feed.py

      - name: Push Repo
        run: |
          git config --global user.name 'evanmendenhall'
          git config --global user.email 'evanmenden@protonmail.com'
          git add .
          git commit -m "Modified Feed"
          if git status | grep 'nothing to commit'; then
            echo "No changes to commit"
          else
            git push
